import os
import dotenv

dotenv.load_dotenv()

LOG_LEVEL = os.getenv('LOG_LEVEL')
CLOUDKARAFKA_BROKERS = os.getenv('CLOUDKARAFKA_BROKERS')
CLOUDKARAFKA_USERNAME = os.getenv('CLOUDKARAFKA_USERNAME')
CLOUDKARAFKA_PASSWORD = os.getenv('CLOUDKARAFKA_PASSWORD')
CLOUDKARAFKA_TOPIC_PREFIX = os.getenv('CLOUDKARAFKA_TOPIC_PREFIX')
FLASK_SECRET_KEY = os.getenv('FLASK_SECRET_KEY')
